# Welcome to Jekyll!
#

# Site settings
title: Lorem Ipsum  
description: |

    Lorem Ipsum is simply dummy text of the printing and typesetting 
    Lorem Ipsum is simply dummy text of the printing and typesetting 
    Lorem Ipsum is simply dummy text of the printing and typesetting 
    Lorem Ipsum is simply dummy text of the printing and typesetting 

    - Lorem Ipsum is simply dummy text of the printing and typesetting 

    Lorem Ipsum is simply dummy text of the printing and typesetting 
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  facebook-official: https://facebook.com/<username>
  email: dsad@yourdomain.com
  instagram: http://yourdomain.com

# Build settings
markdown: kramdown
#sass:
#  style: compressed
